# Generated by Django 4.0 on 2021-12-10 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contestants_of_eight_producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contestant_one', models.CharField(max_length=100)),
                ('contestant_two', models.CharField(max_length=100)),
                ('contestant_three', models.CharField(max_length=100)),
                ('contestant_four', models.CharField(max_length=100)),
                ('contestant_five', models.CharField(max_length=100)),
                ('contestant_six', models.CharField(max_length=100)),
                ('contestant_seven', models.CharField(max_length=100)),
                ('contestant_eight', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='contestants_of_four_producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contestant_one', models.CharField(max_length=100)),
                ('contestant_two', models.CharField(max_length=100)),
                ('contestant_three', models.CharField(max_length=100)),
                ('contestant_four', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='contestants_of_one_vs_one',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contestant_one', models.CharField(max_length=100)),
                ('contestant_two', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
